version: '3.8'

services:
  inteligencia-eleitoral:
    build: .
    container_name: inteligencia_eleitoral_cron
    restart: always
    env_file:
      - .env

  servidor-web-unificado:
    build: .
    container_name: servidor_web_unificado_app
    command: python /app/server_web_unificado.py
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
