-- Script SQL de Alta Performance para o Supabase (PostgreSQL + PostGIS)
-- Projeto: Inteligência Eleitoral - Campanha Wilder Morais (Goiás)

-- 0. Habilita a extensão de Inteligência Geoespacial PostGIS no PostgreSQL/Supabase
CREATE EXTENSION IF NOT EXISTS postgis;

-- 1. Tabela de Municípios de Goiás (com suporte a Coordenadas Geoespaciais PostGIS)
CREATE TABLE IF NOT EXISTS municipios_goias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL UNIQUE,
    eleitores_tse INTEGER DEFAULT 0,
    latitude NUMERIC(10, 6),
    longitude NUMERIC(10, 6),
    geometria GEOMETRY(Point, 4326)
);

-- 2. Tabela de Métricas do Wilder (Metricas de Redes Sociais e Tráfego Pago por Cidade)
CREATE TABLE IF NOT EXISTS metricas_wilder (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data DATE NOT NULL,
    alcance INTEGER DEFAULT 0,
    impressoes INTEGER DEFAULT 0,
    investimento NUMERIC(10, 2) DEFAULT 0.00,
    cliques INTEGER DEFAULT 0,
    cidade TEXT,
    facebook_curtidas_total INTEGER DEFAULT 0,
    facebook_alcance_diario INTEGER DEFAULT 0
);

-- 3. Tabela de Performance de Criativos
CREATE TABLE IF NOT EXISTS criativos_performance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id TEXT,
    midia_url TEXT,
    curtidas INTEGER DEFAULT 0,
    compartilhamentos INTEGER DEFAULT 0,
    engajamento NUMERIC(10, 2) DEFAULT 0.00,
    data_post TIMESTAMP WITH TIME ZONE
);

-- 4. Tabela de Histórico de Concorrentes
CREATE TABLE IF NOT EXISTS concorrentes_historico (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data DATE NOT NULL,
    candidato_nome TEXT NOT NULL,
    seguidores INTEGER DEFAULT 0,
    taxa_engajamento NUMERIC(5, 2) DEFAULT 0.00,
    facebook_seguidores INTEGER DEFAULT 0
);

-- 5. Tabela de Clipping de Notícias
CREATE TABLE IF NOT EXISTS clipping_noticias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    titulo TEXT NOT NULL,
    link TEXT UNIQUE,
    portal TEXT,
    sentimento TEXT,
    resumo TEXT
);

-- 6. Tabela de Monitoramento de Tendências (Google Trends Goiás)
CREATE TABLE IF NOT EXISTS google_trends_goias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    termo TEXT NOT NULL,
    interesse_relativo INTEGER DEFAULT 0,
    regiao_mais_buscada TEXT,
    assuntos_relacionados TEXT
);

-- 7. Tabela de Briefings Diários de Conteúdo & Copiloto do Social Media
CREATE TABLE IF NOT EXISTS briefings_diarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data DATE NOT NULL DEFAULT CURRENT_DATE,
    resumo_cenario TEXT,
    ideias_roteiros TEXT,
    pautas_google_trends TEXT,
    alertas_concorrentes TEXT
);

-- 8. Tabela de Cadastros de Eleitores e Lideranças Locais (CRM Eleitoral Open-Source)
CREATE TABLE IF NOT EXISTS eleitores_cadastrados (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    nome TEXT NOT NULL,
    whatsapp TEXT,
    cidade TEXT NOT NULL,
    bairro TEXT,
    faixa_etaria TEXT,
    pauta_interesse TEXT,
    fonte_origem TEXT DEFAULT 'Instagram DM'
);

-- 9. Tabela de Demandas Populares por Município
CREATE TABLE IF NOT EXISTS demandas_populares (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    cidade TEXT NOT NULL,
    categoria TEXT NOT NULL,
    descricao TEXT NOT NULL,
    nivel_urgencia TEXT DEFAULT 'MÉDIO',
    status_atendimento TEXT DEFAULT 'REGISTRADO'
);

-- 10. Tabela de Métricas do YouTube (Canal Oficial Wilder Morais)
CREATE TABLE IF NOT EXISTS youtube_performance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data DATE NOT NULL,
    inscritos INTEGER DEFAULT 0,
    visualizacoes_totais BIGINT DEFAULT 0,
    videos_totais INTEGER DEFAULT 0,
    visualizacoes_diarias INTEGER DEFAULT 0,
    engajamento_medio NUMERIC(5, 2) DEFAULT 0.00
);

-- 11. Tabela de Top Vídeos do YouTube
CREATE TABLE IF NOT EXISTS youtube_videos_top (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_coleta TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    video_id TEXT NOT NULL,
    titulo TEXT NOT NULL,
    midia_url TEXT,
    visualizacoes INTEGER DEFAULT 0,
    curtidas INTEGER DEFAULT 0,
    comentarios INTEGER DEFAULT 0,
    tipo_video TEXT DEFAULT 'SHORTS'
);

-- 12. Tabela de Radar de Social Listening & Reclamações Populares
CREATE TABLE IF NOT EXISTS reclamacoes_cidadaos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    cidade TEXT NOT NULL,
    pauta_chave TEXT NOT NULL,
    reclamacao_texto TEXT NOT NULL,
    fonte TEXT,
    impacto_politico TEXT DEFAULT 'MÉDIO',
    oportunidade_criativo TEXT
);

-- ===================================================================
-- ÍNDICES PARA ALTA PERFORMANCE DE CONSULTA NO METABASE
-- ===================================================================
CREATE INDEX IF NOT EXISTS idx_metricas_wilder_cidade ON metricas_wilder(cidade);
CREATE INDEX IF NOT EXISTS idx_metricas_wilder_data ON metricas_wilder(data);
CREATE INDEX IF NOT EXISTS idx_concorrentes_data ON concorrentes_historico(data, candidato_nome);
CREATE INDEX IF NOT EXISTS idx_clipping_link ON clipping_noticias(link);
CREATE INDEX IF NOT EXISTS idx_clipping_sentimento ON clipping_noticias(sentimento);
CREATE INDEX IF NOT EXISTS idx_google_trends_termo ON google_trends_goias(termo);
CREATE INDEX IF NOT EXISTS idx_eleitores_cidade ON eleitores_cadastrados(cidade);
CREATE INDEX IF NOT EXISTS idx_eleitores_pauta ON eleitores_cadastrados(pauta_interesse);
CREATE INDEX IF NOT EXISTS idx_demandas_cidade ON demandas_populares(cidade);
CREATE INDEX IF NOT EXISTS idx_youtube_data ON youtube_performance(data);
CREATE INDEX IF NOT EXISTS idx_youtube_video_id ON youtube_videos_top(video_id);
CREATE INDEX IF NOT EXISTS idx_reclamacoes_cidade ON reclamacoes_cidadaos(cidade);
CREATE INDEX IF NOT EXISTS idx_reclamacoes_pauta ON reclamacoes_cidadaos(pauta_chave);

-- ===================================================================
-- COMANDOS DE MIGRAÇÃO PARA EXECUTAR NO SUPABASE SQL EDITOR
-- ===================================================================
CREATE TABLE IF NOT EXISTS reclamacoes_cidadaos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    cidade TEXT NOT NULL,
    pauta_chave TEXT NOT NULL,
    reclamacao_texto TEXT NOT NULL,
    fonte TEXT,
    impacto_politico TEXT DEFAULT 'MÉDIO',
    oportunidade_criativo TEXT
);
