-- Script SQL para criação das tabelas no Supabase (PostgreSQL)
-- Projeto: Inteligência Eleitoral - Campanha Wilder Morais (Goiás)

-- 0. Habilita a extensão de Inteligência Geoespacial PostGIS no PostgreSQL/Supabase
CREATE EXTENSION IF NOT EXISTS postgis;

-- 1. Tabela de Municípios de Goiás (com suporte a Coordenadas Geoespaciais PostGIS)
CREATE TABLE IF NOT EXISTS municipios_goias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    eleitores_tse INTEGER DEFAULT 0,
    latitude NUMERIC(10, 6),
    longitude NUMERIC(10, 6),
    geometria GEOMETRY(Point, 4326)
);

-- 2. Tabela de Métricas do Wilder (Metricas de Redes Sociais e Tráfego Pago por Cidade)
CREATE TABLE IF NOT EXISTS metricas_wilder (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data DATE NOT NULL,
    alcance INTEGER DEFAULT 0,
    impressoes INTEGER DEFAULT 0,
    investimento NUMERIC(10, 2) DEFAULT 0.00,
    cliques INTEGER DEFAULT 0,
    cidade TEXT,
    facebook_curtidas_total INTEGER DEFAULT 0,
    facebook_alcance_diario INTEGER DEFAULT 0
);

-- 3. Tabela de Performance de Criativos
CREATE TABLE IF NOT EXISTS criativos_performance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id TEXT,
    midia_url TEXT,
    curtidas INTEGER DEFAULT 0,
    compartilhamentos INTEGER DEFAULT 0,
    engajamento NUMERIC(10, 2) DEFAULT 0.00,
    data_post TIMESTAMP WITH TIME ZONE
);

-- 4. Tabela de Histórico de Concorrentes
CREATE TABLE IF NOT EXISTS concorrentes_historico (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data DATE NOT NULL,
    candidato_nome TEXT NOT NULL,
    seguidores INTEGER DEFAULT 0,
    taxa_engajamento NUMERIC(5, 2) DEFAULT 0.00,
    facebook_seguidores INTEGER DEFAULT 0
);

-- 5. Tabela de Clipping de Notícias
CREATE TABLE IF NOT EXISTS clipping_noticias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    titulo TEXT NOT NULL,
    link TEXT,
    portal TEXT,
    sentimento TEXT,
    resumo TEXT
);

-- 6. Tabela de Monitoramento de Tendências (Google Trends Goiás)
CREATE TABLE IF NOT EXISTS google_trends_goias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    termo TEXT NOT NULL,
    interesse_relativo INTEGER DEFAULT 0,
    regiao_mais_buscada TEXT,
    assuntos_relacionados TEXT
);

-- ===================================================================
-- COMANDOS DE MIGRAÇÃO (Execute no SQL Editor do Supabase se as tabelas já foram criadas)
-- ===================================================================
CREATE EXTENSION IF NOT EXISTS postgis;
ALTER TABLE municipios_goias ADD COLUMN IF NOT EXISTS latitude NUMERIC(10, 6);
ALTER TABLE municipios_goias ADD COLUMN IF NOT EXISTS longitude NUMERIC(10, 6);
ALTER TABLE municipios_goias ADD COLUMN IF NOT EXISTS geometria GEOMETRY(Point, 4326);
ALTER TABLE metricas_wilder ADD COLUMN IF NOT EXISTS facebook_curtidas_total INTEGER DEFAULT 0;
ALTER TABLE metricas_wilder ADD COLUMN IF NOT EXISTS facebook_alcance_diario INTEGER DEFAULT 0;
ALTER TABLE concorrentes_historico ADD COLUMN IF NOT EXISTS facebook_seguidores INTEGER DEFAULT 0;
