-- Script SQL para criação das tabelas no Supabase (PostgreSQL)
-- Projeto: Inteligência Eleitoral - Campanha Wilder

-- 1. Tabela de Municípios de Goiás
CREATE TABLE IF NOT EXISTS municipios_goias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    eleitores_tse INTEGER DEFAULT 0
);

-- 2. Tabela de Métricas do Wilder
CREATE TABLE IF NOT EXISTS metricas_wilder (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data DATE NOT NULL,
    alcance INTEGER DEFAULT 0,
    impressoes INTEGER DEFAULT 0,
    investimento NUMERIC(10, 2) DEFAULT 0.00,
    cliques INTEGER DEFAULT 0,
    cidade TEXT
);

-- 3. Tabela de Performance de Criativos
CREATE TABLE IF NOT EXISTS criativos_performance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id TEXT,
    midia_url TEXT,
    curtidas INTEGER DEFAULT 0,
    compartilhamentos INTEGER DEFAULT 0,
    engajamento NUMERIC(10, 2) DEFAULT 0.00,
    data_post TIMESTAMP WITH TIME ZONE
);

-- 4. Tabela de Histórico de Concorrentes
CREATE TABLE IF NOT EXISTS concorrentes_historico (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data DATE NOT NULL,
    candidato_nome TEXT NOT NULL,
    seguidores INTEGER DEFAULT 0,
    taxa_engajamento NUMERIC(5, 2) DEFAULT 0.00
);

-- 5. Tabela de Clipping de Notícias
CREATE TABLE IF NOT EXISTS clipping_noticias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    titulo TEXT NOT NULL,
    link TEXT,
    portal TEXT,
    sentimento TEXT,
    resumo TEXT
);
